# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VCS-CMSynergy
version:      1.26
version_from: lib/VCS/CMSynergy.pm
installdirs:  site
requires:
    File::Spec:                    0
    File::Temp:                    0
    IPC::Run3:                     0.01
    Test::More:                    0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
