name:         VCS-CMSynergy
version:      1.27
version_from: lib/VCS/CMSynergy.pm
installdirs:  site
license:      perl
requires:
  File::Spec:                    0
  File::Temp:                    0
  IPC::Run3:                     0.030
  Test::More:                    0
  Time::HiRes:                   0
no_index:
  module:
    - VCS::CMSynergy::ObjectTieHash
  package:
    - VCS::CMSynergy::Traversal
    - Tie::ReadonlyArray
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
